export const REFRESH_RESET_DELAY_MS = 5000;
export const REFRESH_POLL_INTERVAL_MS = 5000;
export const REFRESH_MAX_MONITORING_MS = 60 * 60 * 1000;
export const REFRESH_RETRY_POLL_INTERVAL_MS = REFRESH_POLL_INTERVAL_MS * 2;
