ALTER TABLE public.dashboard_entregadores_incremental_scopes
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.dashboard_entregadores_incremental_scopes
  ADD CONSTRAINT dashboard_entregadores_incremental_scopes_pkey PRIMARY KEY (id);

ALTER TABLE public.dashboard_entregadores_agregado_semanal
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.dashboard_entregadores_agregado_semanal
  ADD CONSTRAINT dashboard_entregadores_agregado_semanal_pkey PRIMARY KEY (id);
